--- 
title: "My post-graduate study work"
author: "Karine Villeneuve"
affiliation: "University of Quebec in Montrealm(UQAM)"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo

---

# Introduction {#intro}

Welcome to my bookdown, a place where I keep step-by-step guides and general informations about my project. 

## About me 

My name is Karine Villeneuve and I am a post-graduate student working at the [lazar microbial ecology lab]() at the Univeristy of Quebec in Montreal. 


My research focuses on microbial communities that live in aquifers. More specifically I am interested in changes happening at the community level according to the seasons and in the migration of microorganism in the subsurface, from recharge to discharge area. 


I began my research in September 2019 after obtaining my bachelor's degree in environmental studies at the University of Sherbrooke. 


This led me on an unpexpected journey from Montreal to Texas. 
